travis:
  secure:
    BINSTAR_TOKEN: LrOMt2wtu/GoV+efXCcCOsZl561m8Psev/cjcDcx6/AnnHkspXGN/hLx7sLiusX9wp6zOiQhzUytW+OLYEsRVtvrN/SkZobzlE0ZnQfxoIRFnlqp9zTlF8OtL2hnVuV/EpH1qGnQFYOhW2RDSTu9ME6QW3royAMVKc99bKT0c9PWIe4p+ntoPvyikTlUvJK44hLFZ+oi6mGa8rKd11p8ZLObFfuZy0gAwMnB9BRMdRzhOJ7rvSd7MeeIMH3vG2hRjG9tHov6Kj9IlkXPtA0I7bU9O2i96//OxUvrKug+flRGmIYj4LsFF4Q5uYiou7i1HMjHY0McIDNWGY3HMyWy2jtdWRNpEgLMtRODKOf2eqD05s5af50WocbFieHYUXARzlAJ4ENj/3TNU/BBoz2F5Q4Pu7DQ50LygO1l++jGmtkvYnQfbKp4r3gcK9bDe3ZNYteSmOgVCjVDvk6eJDLu71BcOEvpGjSsnIJF5Wdb50c1Fb8TBtO27lpn2i8zoYeXh6gX0zR5QLGJsUBDr4KF3OCXabPMN1okYV7g3z0DtwgVhmm3tQnWOZl3LTtt8hPag7JqynD0rZG4QMHA4dOKgHsU6cP1Jg2AxiP12TVJ4VdXJL059IiqWLGQVN6RIIehcwKhPgBAOsajg+rNeZ66TWt0uFHMDvowFHsU+94w+pA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: false
